import {
  IEffortAdjustmentFactor,
  IFunctionPointAttributes,
  ILOC,
} from '@common/interface';

const EFFORT_ADJUSTMENT_FACTOR: IEffortAdjustmentFactor[] = [
  {
    attribute: 'Required software reliability',
    veryLow: 0.75,
    low: 0.88,
    nominal: 1,
    high: 1.15,
    veryHigh: 1.4,
    extraHigh: null,
  },
  {
    attribute: 'Size of application database',
    veryLow: null,
    low: 0.94,
    nominal: 1,
    high: 1.08,
    veryHigh: 1.16,
    extraHigh: null,
  },
  {
    attribute: 'Complexity of the product',
    veryLow: 0.7,
    low: 0.85,
    nominal: 1,
    high: 1.15,
    veryHigh: 1.3,
    extraHigh: 1.65,
  },
  {
    attribute: 'Run-time performance constraints',
    veryLow: null,
    low: null,
    nominal: 1,
    high: 1.11,
    veryHigh: 1.3,
    extraHigh: 1.66,
  },
  {
    attribute: 'Memory constraints',
    veryLow: null,
    low: null,
    nominal: 1,
    high: 1.06,
    veryHigh: 1.21,
    extraHigh: 1.56,
  },
  {
    attribute: 'Volatility of the virtual machine environment',
    veryLow: null,
    low: 0.87,
    nominal: 1,
    high: 1.15,
    veryHigh: 1.3,
    extraHigh: null,
  },
  {
    attribute: 'Required turnabout time',
    veryLow: null,
    low: 0.87,
    nominal: 1,
    high: 1.07,
    veryHigh: 1.15,
    extraHigh: null,
  },
  {
    attribute: 'Analyst capability',
    veryLow: 1.46,
    low: 1.19,
    nominal: 1,
    high: 0.86,
    veryHigh: 0.71,
    extraHigh: null,
  },
  {
    attribute: 'Applications experience',
    veryLow: 1.29,
    low: 1.13,
    nominal: 1,
    high: 0.91,
    veryHigh: 0.82,
    extraHigh: null,
  },
  {
    attribute: 'Software engineer capability',
    veryLow: 1.42,
    low: 1.17,
    nominal: 1,
    high: 0.86,
    veryHigh: 0.7,
    extraHigh: null,
  },
  {
    attribute: 'Virtual machine experience',
    veryLow: 1.21,
    low: 1.1,
    nominal: 1,
    high: 0.9,
    veryHigh: null,
    extraHigh: null,
  },
  {
    attribute: 'Programming language experience',
    veryLow: 1.14,
    low: 1.07,
    nominal: 1,
    high: 0.95,
    veryHigh: null,
    extraHigh: null,
  },
  {
    attribute: 'Application of software engineering methods',
    veryLow: 1.24,
    low: 1.1,
    nominal: 1,
    high: 0.91,
    veryHigh: 0.82,
    extraHigh: null,
  },
  {
    attribute: 'Use of software tools',
    veryLow: 1.24,
    low: 1.1,
    nominal: 1,
    high: 0.91,
    veryHigh: 0.83,
    extraHigh: null,
  },
  {
    attribute: 'Required development schedule',
    veryLow: 1.23,
    low: 1.08,
    nominal: 1,
    high: 1.04,
    veryHigh: 1.1,
    extraHigh: null,
  },
] as const;

const LINES_OF_CODE: ILOC[] = [
  { language: 'ABAP (SAP) ', avarage: 28, median: 18, low: 16, high: 60 },
  { language: 'ASP', avarage: 18, median: 51, low: 60, high: 15 },
  { language: 'Assembler ', avarage: 51, median: 54, low: 15, high: 69 },
  { language: 'Brio ', avarage: 54, median: 119, low: 69, high: 25 },
  { language: 'C ', avarage: 119, median: 98, low: 25, high: 320 },
  { language: 'C++ ', avarage: 98, median: 14, low: 320, high: 13 },
  { language: 'C# ', avarage: 14, median: 14, low: 13, high: 16 },
  { language: 'COBOL ', avarage: 14, median: 97, low: 16, high: 39 },
  {
    language: 'Cognos Impromptu Scripts ',
    avarage: 97,
    median: 99,
    low: 39,
    high: 333,
  },
  {
    language: 'Cross System Products (CSP) ',
    avarage: 99,
    median: 50,
    low: 333,
    high: 25,
  },
  { language: 'Cool:Gen/IEF ', avarage: 50, median: 53, low: 25, high: 80 },
  { language: 'Datastag', avarage: 53, median: 54, low: 80, high: 29 },
  { language: 'Excel ', avarage: 54, median: 59, low: 29, high: 70 },
  { language: 'Focus ', avarage: 59, median: 61, low: 70, high: 23 },
  { language: 'HTML ', avarage: 61, median: 55, low: 23, high: 297 },
  { language: 'J2EE ', avarage: 55, median: 47, low: 297, high: 30 },
  { language: 'Java ', avarage: 47, median: 42, low: 30, high: 100 },
  { language: 'JavaScript ', avarage: 42, median: 20, low: 100, high: 10 },
  { language: 'JCL ', avarage: 20, median: 18, low: 10, high: 38 },
  { language: 'LINC I', avarage: 18, median: 32, low: 38, high: 10 },
  { language: 'Lotus Notes ', avarage: 32, median: 24, low: 10, high: 82 },
  { language: 'Natural ', avarage: 24, median: 71, low: 82, high: 31 },
  { language: '.NET ', avarage: 71, median: 65, low: 31, high: 157 },
  { language: 'Oracle ', avarage: 65, median: 209, low: 157, high: 131 },
  { language: 'Perl ', avarage: 209, median: 191, low: 131, high: 315 },
  { language: 'PL/I ', avarage: 191, median: 43, low: 315, high: 45 },
  { language: 'PL/SQL ', avarage: 43, median: 45, low: 45, high: 45 },
  { language: 'Powerbuilder ', avarage: 45, median: 34, low: 45, high: 14 },
  { language: 'REXX ', avarage: 34, median: 40, low: 14, high: 48 },
  { language: 'Sabretalk ', avarage: 40, median: 46, low: 48, high: 15 },
  { language: 'SAS ', avarage: 46, median: 49, low: 15, high: 67 },
  { language: 'Siebel ', avarage: 49, median: 53, low: 67, high: 14 },
  { language: 'SLOGAN ', avarage: 53, median: 53, low: 14, high: 134 },
  { language: 'SQL ', avarage: 53, median: 47, low: 134, high: 31 },
  { language: 'VB.NET ', avarage: 47, median: 53, low: 31, high: 63 },
  { language: 'Visual Basic ', avarage: 53, median: 62, low: 63, high: 25 },
] as const;

const FUNCTION_POINT_ATTRIBUTES: IFunctionPointAttributes = {
  'User Input': {
    low: 3,
    avarage: 4,
    high: 6,
  },
  'User Output': {
    low: 4,
    avarage: 5,
    high: 7,
  },
  'User Query': {
    low: 3,
    avarage: 4,
    high: 6,
  },
  'Internal Files': {
    low: 7,
    avarage: 10,
    high: 15,
  },
  'External Interfaces': {
    low: 5,
    avarage: 7,
    high: 10,
  },
} as const;

export { EFFORT_ADJUSTMENT_FACTOR, LINES_OF_CODE, FUNCTION_POINT_ATTRIBUTES };
